Repository codeitFE11-part3-team7/wikid, pull requests merged in 2024-12, with the labels that each got.

#8 #7 공통 컬러 및 폰트 추가
  components/DarkmodeToggle.tsx
  pages/_app.tsx
  pages/_document.tsx
  postcss.config.js
  styles/globals.css
  tailwind.config.ts
Labels: 💄 스타일, 🧪 테스트

#12 #11 eslint 규칙 세분화
  .eslintrc.json
  .vscode/settings.json
  components/DarkmodeToggle.tsx
  eslint.config.cjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  tsconfig.json
Labels: ⚙️ 세팅

#18 🔧 delete 'cr' prettier 에러 - rules 추가로 해결
  .prettierrc
Labels: ⚙️ 세팅

#20 💄 tailwind 반응형 breakpoints 설정
  tailwind.config.ts
Labels: 💄 스타일

#25 #24_test 페이지 생성
  pages/test/index.tsx
Labels: ✨ 신규 기능

#23 ✨ 공통 버튼 컴포넌트 추가
  components/Button.tsx
  pages/test/index.tsx
Labels: 📁 컴포넌트

#27 #26 link 컴포넌트
  components/LinkBar.tsx
  pages/test/index.tsx
  public/icon/icon-link.svg
Labels: 📁 컴포넌트

#35 #16 메뉴 컴포넌트 / Dropdown 컴포넌트
  components/Dropdown.tsx
  components/Menu.tsx
  package-lock.json
  package.json
  pages/test/index.tsx
  public/icon/icon-arrowdown.svg
Labels: 📁 컴포넌트

#33 ✨ 검색창 컴포넌트 제작
  components/SearchInput.tsx
  public/icon/icon-search.svg
  tsconfig.json
Labels: 📁 컴포넌트

#38 #28 pagination 컴포넌트
  .gitignore
  components/Pagination/Pagination.tsx
  components/Pagination/PaginationButton.tsx
  pages/test/pagination.tsx
  public/icon/icon-arrow.svg
  tailwind.config.ts
Labels: 📁 컴포넌트

#37 Feature/#29 텍스트 에디터 - quill 추가
  components/TextEditor.tsx
  package-lock.json
  package.json
  pages/test/editor.tsx
  styles/globals.css
Labels: 📁 컴포넌트

#51 #50 tailwind 스타일 오류
  pages/_document.tsx
  styles/globals.css
  tailwind.config.ts
Labels: 🐛 버그, 💄 스타일

#54 🔧 tailwind config - container 설정 추가
  tailwind.config.ts
Labels: ⚙️ 세팅

#42 Feature/#36 gnb 컴포넌트
  components/Dropdown.tsx
  components/Headers/Alarm.tsx
  components/Headers/GNB.tsx
  components/Headers/Headers.tsx
  components/Headers/Login.tsx
  components/Menu.tsx
  hooks/useCheckMobile.tsx
  hooks/useOutsideClick.tsx
  package.json
  pages/test/Headers/index.tsx
  public/icon/icon-alarm.svg
  public/icon/icon-menu.svg
  public/icon/icon-profile.svg
  public/images/logo.svg
Labels: 📁 컴포넌트

#52 #48 heart 컴포넌트
  components/Heart/Heart.tsx
  components/Heart/HeartIcon.tsx
  pages/test/heart.tsx
Labels: ✨ 신규 기능, 📁 컴포넌트

#56 Feature/#55 axios instance
  components/DisconnectionModal.tsx
  components/ImageUploadModal.tsx
  components/Modal.tsx
  components/UnsavedChangesModal.tsx
  components/WikiQuizModal.tsx
  lib/axios-client.ts
  pages/test/modal.tsx
  public/icon/icon-camera.png
  public/icon/icon-close.svg
  public/icon/icon-lock.png
  tsconfig.json
Labels: 📡 API

#58 Feature/#57 auth api
  pages/test/auth.tsx
  services/api/auth.ts
Labels: 📡 API

#66 🔨 _app.tsx 에 공통 헤더 추가
  pages/_app.tsx
Labels: 📄 페이지

#68 #45 board list 컴포넌트
  components/Heart/Heart.tsx
  components/Heart/HeartIcon.tsx
  pages/boards/components/BoardItem.tsx
  pages/boards/components/BoardList.tsx
  pages/test/boardTable.tsx
Labels: 💫 업데이트, 📁 컴포넌트

#72 Feature/#71 blank 컴포넌트
  package-lock.json
  pages/wiki/components/Blank.tsx
Labels: 📁 컴포넌트

#76 Feature/#49 로그인 페이지
  pages/login/index.tsx
Labels: 📄 페이지

#64 Feature/#43 게시물 등록하기 페이지
  components/DarkmodeToggle.tsx
  pages/addboard.tsx
  styles/globals.css
Labels: 📄 페이지

#80 #79 e slint 강화 및 규칙 추가
  .eslintrc.js
  .prettierrc
  .vscode/settings.json
  components/Button.tsx
  components/Dropdown.tsx
  components/Headers/Alarm.tsx
  components/Headers/Headers.tsx
  components/Headers/Login.tsx
  components/Heart/HeartIcon.tsx
  components/ImageUploadModal.tsx
  components/LinkBar.tsx
  components/Menu.tsx
  components/Modal.tsx
  components/Pagination/Pagination.tsx
  components/Pagination/PaginationButton.tsx
  components/SearchInput.tsx
  components/SnackBar.tsx
  components/WikiQuizModal.tsx
  eslint.config.cjs
  hooks/useCheckMobile.tsx
  lib/axios-client.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/addboard.tsx
  pages/boards/components/BoardList.tsx
  pages/test/auth.tsx
  pages/test/modal.tsx
  services/api/auth.ts
Labels: ⚙️ 세팅, 💫 업데이트, 🔨수정해주세요, 🚨 긴급

#82 Feature/#73 contents header 컴포넌트
  components/Dropdown.tsx
  components/Headers/Login.tsx
  components/LinkBar.tsx
  components/Menu.tsx
  package-lock.json
  pages/test/wiki/index.tsx
  pages/wiki/components/Blank.tsx
  pages/wiki/components/ContentHeader.tsx
Labels: 📁 컴포넌트

#97 Feature/#63 내 위키 페이지
  .gitignore
  package-lock.json
  package.json
  pages/addboard/index.tsx
  pages/wiki/[code].tsx
  pages/wiki/components/Contents.tsx
Labels: 📄 페이지

#85 #84 comment form 컴포넌트
  pages/boards/components/CommentForm.tsx
  pages/test/commentForm.tsx
  services/api/auth.ts
Labels: 📁 컴포넌트

#99 ✨ api 요청 예시, 테스트 페이지 통합
  pages/test/api.tsx
  pages/test/auth.tsx
  services/api/auth.ts
  services/api/profileAPI.ts
Labels: 📡 API

#90 #46 자유게시판 get rest api
  components/Headers/Headers.tsx
  next.config.ts
  package-lock.json
  pages/boards/index.tsx
  services/api/boardsAPI.ts
Labels: ✨ 신규 기능, 💫 업데이트, 📡 API

#87 Feature/#41 회원가입 페이지
  hooks/useValidation.tsx
  pages/signup/index.tsx
Labels: 📡 API

#92 ✨ 로그인 API 작업
  pages/login/index.tsx
Labels: 📡 API

#86 #81 comment 컴포넌트
  pages/boards/components/Comment.tsx
  pages/test/comment.tsx
  pages/test/commentForm.tsx
  public/icon/icon-delete.svg
  public/icon/icon-write.svg
Labels: 📁 컴포넌트

#110 #109 modal 디테일 스타일링
  components/Input.tsx
  components/Modal/DisconnectionModal.tsx
  components/Modal/ImageUploadModal.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalDefault.tsx
  components/Modal/UnsavedChangesModal.tsx
  components/Modal/WikiQuizModal.tsx
  public/icon/icon-camera.png
  public/icon/icon-camera.svg
  public/icon/icon-lock.png
Labels: ♻️ 리팩토링, 💄 스타일, 📁 컴포넌트, 🫠 중복

#75 Feature/#74 퀴즈 모달 컴포넌트
  components/DisconnectionModal.tsx
  components/Input.tsx
  components/Modal/DisconnectionModal.tsx
  components/Modal/ImageUploadModal.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalDefault.tsx
  components/Modal/UnsavedChangesModal.tsx
  components/Modal/WikiQuizModal.tsx
  components/UnsavedChangesModal.tsx
  components/WikiQuizModal.tsx
  pages/_document.tsx
  pages/test/modal.tsx
  public/icon/icon-camera.png
  public/icon/icon-camera.svg
  public/icon/icon-lock.png
  public/icon/icon-lock.svg
Labels: 💫 업데이트

#107 ✨ 공개엔드포인트 추가 및 테스트 페이지 수정
  lib/axios-client.ts
  pages/test/api.tsx
Labels: 📡 API

#108 Feature/#102 위키 목록 페이지 리스트 아이템 컴포넌트
  pages/wikilist/ListItem.tsx
Labels: 📁 컴포넌트

#103 #94 게시글 상세 전체 페이지
  pages/boards/[articleId].tsx
  pages/boards/components/BoardDetailCard.tsx
  pages/boards/components/ButtonIcon.tsx
  pages/updateboard/[articleId].tsx
Labels: 💄 스타일, 📄 페이지

#100 #93 게시글 상세 본문 컴포넌트
  README.md
  pages/boards/[articleId].tsx
Labels: 💄 스타일, 📁 컴포넌트

#115 💄 인풋컴포넌트 너비 props로 지정
  components/Input.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
Labels: 💄 스타일

#116 Feature/#112 검색창 아이콘 오류 수정
  components/SearchInput.tsx
Labels: 💄 스타일

#114 ✨ 계정 설정 페이지 UI API
  pages/mypage/index.tsx
  services/api/auth.ts
Labels: 📡 API, 📄 페이지

#113 Feature/#67 위키 목록 페이지
  components/EmptyList.tsx
  components/Pagination/PaginationButton.tsx
  next.config.ts
  package-lock.json
  pages/wikilist/index.tsx
  public/images/empty.png
Labels: 📄 페이지

#123 Feature/#118 로그인 상태 전역관리 헤더
  components/Headers/Headers.tsx
  components/Headers/Login.tsx
  components/Menu.tsx
  context/ProfileContext.tsx
  pages/_app.tsx
Labels: ♻️ 리팩토링, 💫 업데이트, 📡 API

#122 #120 에디터 컨텐츠 view 컴포넌트
  components/EditorViewer.tsx
  styles/globals.css
Labels: 💄 스타일, 📁 컴포넌트

#119 🔨 api 연결 및 확인, 에디터 높이값 수정
  pages/addboard/index.tsx
Labels: 📡 API

#124 #101 snack bar 텍스트 커스텀 가능하게 수정
  components/SnackBar.tsx
  pages/test/index.tsx
Labels: 💫 업데이트, 📁 컴포넌트

#129 Feature/#83 프로필 컴포넌트
  components/UserProfile.tsx
  pages/test/profile.tsx
  public/icon/icon-camera.svg
  public/icon/icon-collapse.svg
  public/icon/icon-expand.svg
  public/images/image-profile.png
Labels: 📁 컴포넌트

#149 Feature/#131 위키 페이지 api 연동 및 완성
  components/Headers/Headers.tsx
  components/Headers/Login.tsx
  components/Modal/WikiQuizModal.tsx
  components/UserProfile.tsx
  context/ProfileContext.tsx
  next.config.ts
  pages/wiki/[code].tsx
  pages/wiki/components/Blank.tsx
  pages/wiki/components/ContentHeader.tsx
  pages/wiki/components/Contents.tsx
  tsconfig.json
Labels: 💄 스타일, 📡 API, 📄 페이지

#152 Feature/#146 axios client 수정
  lib/axios-client.ts
Labels: 📡 API

#148 🏷️ 게시글 작성 타입 수정
  pages/addboard/index.tsx
Labels: ♻️ 리팩토링

#150 🏷️ 위키 목록, 목록 아이템 타입 수정
  pages/wikilist/ListItem.tsx
  pages/wikilist/index.tsx
Labels: ♻️ 리팩토링

#158 🚚 context와 hook 분리
  components/Headers/Headers.tsx
  context/ProfileContext.tsx
  hooks/useProfileContext.tsx
Labels: ♻️ 리팩토링

#169 🐛 rest props 타입 정의 추가
  components/Button.tsx
Labels: 🐛 버그, 🚨 긴급

#161 Feature/#160 Modal Type 수정
  components/Modal/ImageUploadModal.tsx
  components/Modal/Modal.tsx
  components/Modal/WikiQuizModal.tsx
Labels: ♻️ 리팩토링

#171 🐛 이미지 경로 추가
  next.config.ts
Labels: 🐛 버그, 🚨 긴급

#140 Feature/#128 하트 post 기능
  components/Heart/Heart.tsx
  pages/boards/[articleId].tsx
  pages/boards/components/BoardDetailCard.tsx
Labels: ✨ 신규 기능, 🐛 버그, 💫 업데이트, 📡 API

#163 Feature/#162 프로필 컴포넌트 인풋 수정
  components/UserProfile.tsx
  pages/_app.tsx
  pages/_document.tsx
Labels: ♻️ 리팩토링

#173 Feature/#172 profile 타입 분리
  components/Headers/Login.tsx
  context/ProfileContext.tsx
  pages/wiki/[code].tsx
  pages/wiki/components/Contents.tsx
  types/profile.ts
Labels: ♻️ 리팩토링

#175 Feature/#136 게시물 등록 썸네일 등록 추가
  components/Modal/ImageUploadModal.tsx
  pages/addboard/index.tsx
  pages/boards/[articleId].tsx
  pages/boards/components/Comment.tsx
  pages/wikilist/ListItem.tsx
  tsconfig.json
Labels: ✨ 신규 기능, 📄 페이지

#177 Feature/#176 모달 불필요한 타입체크 제거
  components/Modal/Modal.tsx
Labels: ♻️ 리팩토링

#183 Feature/#182 빌드시 발생하는 에러 수정
  components/UserProfile.tsx
  context/ProfileContext.tsx
  hooks/useTimer.tsx
  pages/boards/[articleId].tsx
  pages/wiki/components/Contents.tsx
Labels: ♻️ 리팩토링, 🐛 버그

#184 Feature/#178 빌드 에러 수정
  .eslintignore
  .eslintrc.js
  components/DayPicker.tsx
  components/EditorViewer.tsx
  components/EmptyList.tsx
  components/Headers/Headers.tsx
  components/Headers/Login.tsx
  components/Heart/Heart.tsx
  components/Input.tsx
  components/Modal/ImageUploadModal.tsx
  components/Modal/ModalDefault.tsx
  components/SearchInput.tsx
  components/SnackBar.tsx
  components/UserProfile.tsx
  pages/boards/[articleId].tsx
  pages/boards/components/BoardCard.tsx
  pages/boards/components/BoardDetailCard.tsx
  pages/boards/components/BoardItem.tsx
  pages/boards/components/Comment.tsx
  pages/boards/components/CommentForm.tsx
  pages/boards/index.tsx
  pages/index.tsx
  pages/updateboard/[articleId].tsx
  pages/wiki/[code].tsx
  pages/wiki/components/Contents.tsx
  pages/wikilist/ListItem.tsx
  services/api/boardsAPI.ts
  services/api/userInfoAPI.ts
  styles/globals.css
  tsconfig.json
  types/board.ts
Labels: 🐛 버그

#186 feature/#185 - 위키 목록 페이지 리팩토링
  .eslintrc.js
  components/wikiList.page/ListItem.tsx
  package-lock.json
  package.json
  pages/wikilist/index.tsx
Labels: ♻️ 리팩토링

#192 Feature/#191 위키페이지 스타일 수정
  components/wiki.page/ContentHeader.tsx
  components/wiki.page/Contents.tsx
  pages/wiki/[code].tsx
Labels: 💄 스타일

#203 Feature/#201 몇 분 후 위키 수정 가능한지 알려주는 기능
  components/wiki.page/ContentHeader.tsx
  components/wiki.page/Contents.tsx
Labels: ✨ 신규 기능, 💫 업데이트

#198 Feature/#187 유저 프로필 리팩토링
  components/UserProfile.tsx
  hooks/useExpandedState.ts
  hooks/useProfileImage.ts
  types/profile.ts
Labels: ♻️ 리팩토링

#202 Feature/#199 스피너 제작
  components/Spinner.tsx
  components/UserProfile.tsx
Labels: 📁 컴포넌트

#205 Feature/#126 코멘트 등록 시 snackbar 나오게 수정
  components/boards.page/BoardDetailCard.tsx
  components/boards.page/Comment.tsx
  pages/boards/[articleId].tsx
  pages/boards/index.tsx
  services/api/commentAPI.ts
  types/board.ts
Labels: 💫 업데이트

#211 Feature/#132 게시글 검색 결과 없을 때 결과없음 노출
  components/EmptyList.tsx
  pages/boards/index.tsx
  public/images/empty.png
  public/images/empty.svg
Labels: 💫 업데이트, 💄 스타일

#200 Feature/#193 위키 생성하기 비로그인시 작업
  components/wiki.page/Blank.tsx
  components/wiki.page/ContentHeader.tsx
  components/wiki.page/Contents.tsx
Labels: ♻️ 리팩토링, 💫 업데이트

#214 Feature/#212 다크모드 토글
  components/DarkmodeToggle.tsx
  components/Headers/Headers.tsx
  pages/_app.tsx
  public/icon/icon-dark.svg
  public/icon/icon-light.svg
Labels: 💫 업데이트, 💄 스타일

#196 Feature/#195 위키 목록 페이지 추가 리팩토링 및 기능 추가
  components/wikiList.page/ListItem.tsx
  constants/terms.ts
  hooks/useSanckBar.tsx
  pages/wikilist/index.tsx
  services/api/profileAPI.ts
Labels: ♻️ 리팩토링, 💫 업데이트

#213 ⚡️ 회원가입/ 로그인 성공시 스낵바로 표시
  pages/login/index.tsx
  pages/signup/index.tsx
  services/api/auth.ts
Labels: 💫 업데이트

#216 #137 자유게시판 SSR 패칭 적용
  pages/boards/index.tsx
Labels: 💫 업데이트

#206 🐛 비밀번호 변경되지 않은 오류 수정
  pages/mypage/index.tsx
Labels: 🐛 버그

#220 Feature/#219 2차 테스팅 배포
  .eslintrc.js
  components/DarkmodeToggle.tsx
  components/DayPicker.tsx
  components/EmptyList.tsx
  components/Headers/Headers.tsx
  components/Input.tsx
  components/Modal/WikiQuizModal.tsx
  components/Spinner.tsx
  components/UserProfile.tsx
  components/boards.page/BoardDetailCard.tsx
  components/boards.page/Comment.tsx
  components/wiki.page/Blank.tsx
  components/wiki.page/ContentHeader.tsx
  components/wiki.page/Contents.tsx
  components/wikiList.page/ListItem.tsx
  constants/terms.ts
  hooks/modal/useKeyboardVisibilty.tsx
  hooks/modal/useQuiz.tsx
  hooks/useExpandedState.ts
  hooks/useProfileImage.ts
  hooks/useSanckBar.tsx
  hooks/useSnackBar.tsx
  lib/axios-client.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/addboard/index.tsx
  pages/boards/[articleId].tsx
  pages/boards/index.tsx
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
  pages/updateboard/[articleId].tsx
  pages/wiki/[code].tsx
  pages/wikilist/index.tsx
  public/icon/icon-dark.svg
  public/icon/icon-light.svg
  public/images/empty.png
  public/images/empty.svg
  services/api/auth.ts
  services/api/boardsAPI.ts
  services/api/commentAPI.ts
  services/api/imageAPI.ts
  services/api/profileAPI.ts
  types/board.ts
  types/modal.ts
  types/profile.ts
Labels: 💫 업데이트

#227 Feature/#224 QA-프로필컴포넌트
  components/UserProfile.tsx
Labels: ♻️ 리팩토링, 💄 스타일

#226 Feature/#221 QA - 게시글 등록 위키 목록
  components/FullCoverSpinner.tsx
  components/TextEditor.tsx
  components/wikiList.page/ListItem.tsx
  pages/addboard/index.tsx
  pages/wikilist/index.tsx
  tailwind.config.ts
Labels: 🐛 버그, 💄 스타일

#230 feature/#228 - 404 페이지, 에러 컴포넌트
  components/ErrorMessage.tsx
  components/Svg/IconFaceDizzy.tsx
  pages/404.tsx
  public/icon/icon-face-dizzy.svg
Labels: 📁 컴포넌트, 📄 페이지

#232 Feature/#229 qa 게시판 목록게시판 상세
  components/DarkmodeToggle.tsx
  components/boards.page/BoardDetailCard.tsx
  components/boards.page/BoardList.tsx
  components/boards.page/Comment.tsx
  pages/boards/[articleId].tsx
  pages/boards/index.tsx
  pages/updateboard/[articleId].tsx
  types/board.ts
  utils/dateConversion.ts
Labels: 💫 업데이트

#233 Feature/#223 qa 모달
  components/Modal/ImageUploadModal.tsx
  components/Modal/Modal.tsx
  components/Modal/WikiQuizModal.tsx
Labels: ♻️ 리팩토링, 💄 스타일

#234 🐛 회원가입 검증 오류 수정, 활성화 조건 개선
  components/Input.tsx
  hooks/useValidation.tsx
  pages/signup/index.tsx
  public/icon/icon-eye-off.svg
  public/icon/icon-eye.svg
  services/api/auth.ts
Labels: 🐛 버그

#244 ⚡️ 패스워드 변경 안내문구
  pages/mypage/index.tsx
Labels: 💫 업데이트

#237 Feature/#218 모든 로딩 상태 로딩 컴포넌트 사용
  components/boards.page/CommentEmpty.tsx
  pages/boards/[articleId].tsx
  pages/boards/index.tsx
Labels: 💫 업데이트, 📁 컴포넌트

#239 feature/#238 게시글 작성시 썸네일 등록 안되는 오류
  pages/addboard/index.tsx
Labels: 🐛 버그

#242 feature/#240 메인 화면 가로 스크롤 생기는 문제
  pages/index.tsx
  styles/globals.css
Labels: 🐛 버그, 💄 스타일

#248 Feature/#246 qa 메인
  pages/index.tsx
  public/favicon.ico
  public/images/empty.svg
  public/images/img-alert.svg
  public/images/img-bell.png
  public/images/img-bell.svg
  public/images/img-belt.png
  public/images/img-belt.svg
  public/images/img-bg-bottom.svg
  public/images/img-comment.svg
  public/images/img-text-dark.png
  public/images/img-text-dark.svg
  public/images/img-text-green.png
  public/images/img-text-green.svg
  public/images/img-text-white.png
  public/images/img-text-white.svg
  public/images/img-wiki.png
  public/images/img-wiki.svg
  public/images/img-write.png
  public/images/img-write.svg
Labels: 🐛 버그, 💄 스타일

#251 Feature/#250 피드백 수정 텍스트 넘어감프로필 안보임 등
  components/EditorViewer.tsx
  components/boards.page/BoardDetailCard.tsx
  components/boards.page/Comment.tsx
Labels: 🐛 버그, 💄 스타일

#243 Feature/#217 스낵바 훅 사용 및 스낵바 공통으로 app에 배치
  components/Headers/Login.tsx
  components/Modal/ImageUploadModal.tsx
  components/SnackBar.tsx
  components/boards.page/BoardDetailCard.tsx
  components/wiki.page/ContentHeader.tsx
  components/wiki.page/Contents.tsx
  context/SnackBarContext.tsx
  hooks/useSanckBar.tsx
  hooks/useSnackBar.tsx
  pages/_app.tsx
  pages/addboard/index.tsx
  pages/boards/[articleId].tsx
  pages/boards/index.tsx
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
  pages/updateboard/[articleId].tsx
  pages/wikilist/index.tsx
  services/api/auth.ts
Labels: ♻️ 리팩토링, 💫 업데이트

#247 Feature/#245_QA-프로필컴포넌트관련
  components/UserProfile.tsx
Labels: ♻️ 리팩토링, 🐛 버그, 💄 스타일

#254 Feature/#253 qa 로그인버튼 비활성화
  pages/login/index.tsx
  pages/mypage/index.tsx
  services/api/profileAPI.ts
Labels: ✨ 신규 기능, 🐛 버그

#260 Feature/#255 QA 위키 목록 페이지 UI 수정
  components/LinkBar.tsx
  components/Svg/IconLink.tsx
  components/wikiList.page/ListItem.tsx
  public/images/empty.png
  public/images/empty.svg
Labels: 🐛 버그, 💄 스타일

#268 feature/#266 데이터 패치 에러 컴포넌트 적용
  components/ErrorMessage.tsx
  pages/addboard/index.tsx
  pages/wikilist/index.tsx
Labels: 💫 업데이트

#267 #257 scale 인터랙션 globals 분리 및 페이지네이션 인터랙선 추가
  components/Pagination/PaginationButton.tsx
  styles/globals.css
Labels: 💫 업데이트, 💄 스타일

#269 Feature/#259 아이폰 16 버전 이상 사파리에서 is authenticated 상태 체크
  components/Headers/Login.tsx
  context/ProfileContext.tsx
  pages/login/index.tsx
  services/api/auth.ts
Labels: 🐛 버그, 💫 업데이트

#252 Feature/#249 qa 달력 인풋창
  components/DayPicker.tsx
  components/Input.tsx
  components/SearchInput.tsx
  pages/index.tsx
Labels: 🐛 버그, 💫 업데이트

#264 Feature/#256 위키페이지 로딩스피너 오류 컴포넌트 적용
  components/wiki.page/Contents.tsx
  pages/wiki/[code].tsx
Labels: ♻️ 리팩토링, 💫 업데이트

#272 #262 패칭에러 및 콘솔로그 제거 후 snackbar교체
  pages/boards/[articleId].tsx
  pages/boards/index.tsx
Labels: 💫 업데이트

#270 Feature/#263 boards page boards components style 디테일 체크
  components/Pagination/PaginationButton.tsx
  components/boards.page/BoardCard.tsx
  components/boards.page/BoardDetailCard.tsx
  components/boards.page/ButtonIcon.tsx
  components/boards.page/Comment.tsx
  components/boards.page/CommentForm.tsx
  pages/boards/[articleId].tsx
  pages/boards/index.tsx
Labels: 💄 스타일

#276 #275 인증 상태와 프로필 가져오는 로직 분리
  components/wiki.page/Contents.tsx
  context/ProfileContext.tsx
  hooks/useAuth.ts
  hooks/useProfile.ts
Labels: 🐛 버그, 💫 업데이트, 📡 API, 🔄 커스텀 훅

#277 #261 다크모드에 어울리게 변경
  components/Headers/Headers.tsx
  components/Input.tsx
  components/LinkBar.tsx
  components/SnackBar.tsx
  components/UserProfile.tsx
  components/boards.page/BoardCard.tsx
  components/boards.page/BoardDetailCard.tsx
  components/boards.page/BoardList.tsx
  components/boards.page/Comment.tsx
  components/wikiList.page/ListItem.tsx
  pages/_app.tsx
  styles/globals.css
  tailwind.config.ts
Labels: 💄 스타일

#279 Feature/#278 qa 반영
  components/Dropdown.tsx
  components/boards.page/BoardDetailCard.tsx
  components/boards.page/Comment.tsx
  components/boards.page/CommentForm.tsx
  context/SnackBarContext.tsx
  pages/boards/index.tsx
Labels: 💄 스타일

#273 Feature/#265 추가기능 알림 기능
  components/Headers/Alarm.tsx
  components/Headers/Headers.tsx
  components/Headers/Login.tsx
  components/Menu.tsx
  components/Notification/NorificationBox.tsx
  components/Notification/NotificationContents.tsx
  components/Notification/NotificationWrapper.tsx
  pages/wiki/[code].tsx
  styles/globals.css
Labels: ✨ 신규 기능, 📁 컴포넌트

#285 Feature/#284 오타 수정
  components/Headers/Alarm.tsx
  components/wiki.page/Contents.tsx
  pages/_app.tsx
Labels: 💄 스타일

#281 Feature/#280 qa 반영 메인이미지 모바일
  components/Input.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/login/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
  public/images/img-bell.png
  public/images/img-belt.png
  public/images/img-belt1.png
  public/images/img-belt2.png
  public/images/img-belt3.png
  public/images/img-belt4.png
  public/images/img-text-green.png
  public/images/img-text-white.png
  styles/globals.css
Labels: ✨ 신규 기능, 🐛 버그, 💄 스타일

#283 Feature/#282 qa 모달및유저프로필
  components/Modal/Modal.tsx
  components/Modal/WikiQuizModal.tsx
  components/UserProfile.tsx
  hooks/modal/useKeyboardVisibilty.tsx
Labels: 💫 업데이트, 💄 스타일

#290 ✨ 프로필이 없을 때 내 위키 오류페이지
  components/MyWikiError.tsx
  pages/wiki/[code].tsx
Labels: 🐛 버그, 📁 컴포넌트

#289 💄 이미지파일 교체 비번변경시 초 삭제, 로그아웃상태
  components/Input.tsx
  pages/index.tsx
  pages/mypage/index.tsx
  pages/signup/index.tsx
  public/images/img-bell.png
  public/images/img-belt1.png
  public/images/img-belt2.png
  public/images/img-belt3.png
  public/images/img-belt4.png
  public/images/img-text-dark.png
  public/images/img-text-green.png
  public/images/img-text-white.png
  public/images/img-wiki.png
  public/images/img-write.png
Labels: 💫 업데이트, 💄 스타일

#291 Feature/#287 qa 프로필
  components/UserProfile.tsx
  hooks/useProfileImage.ts
Labels: ♻️ 리팩토링, 💄 스타일

#294 💄 회원가입 중복된 이름 경고문구 변경
  services/api/auth.ts
Labels: 💫 업데이트

#295 feature/#293 에디터 리스트 스타일 오류 수정
  styles/globals.css
Labels: 🐛 버그, 💄 스타일

#297 Feature/#296 다크모드 모바일 오른쪽 마진
  components/Headers/Headers.tsx
Labels: 💄 스타일

#299 feature/#298 에디터 리스트 스타일 오류 수정
  styles/globals.css
Labels: 🐛 버그, 💄 스타일
